### PR TITLE
Fixed headings and added demo

### LINKED ISSUE #19: demo please
The readme should AT LEAST feature a screenshot of the datepicker in action. Otherwise - a demo would be nice.

### PR DESCRIPTION
**Pull request by MartinMuzatko**
only one h1 is allowed usually for valid HTML.
Also, this fixes #19

### CODE REVIEW

**Comment by tjohnn** [comment]
Hi @MartinMuzatko thanks for your contribution, I have not had enough time to work on this recently. The demo does not look good on my browser https://unsee.cc/95695215/. Is it the same there? What can we do about it?

**Comment by MartinMuzatko** [comment]
Yep. the width of the calendar is hardcoded. I tried to use the property `width` as documented, but that only changes the input size - very confusing. There is no extra CSS that influences the sandbox example.
Am I missing some CSS maybe?

Thanks in advance and thanks for your feedback.

**Comment by tjohnn** [comment]
Does it look like this if you use it in a project? It doesn't look scattered like this if I use it in a project though. I can implicitly increase the width if it is too small.
By the way, do you feel it is okay to allow explicit changing of the calendar width based on properties?

**Comment by tjohnn** [comment]
Hmm, I feel the calendar box itself should have a fixed with though, since anyone would be good with it as far as it's ports are not looking staggered as they are in that picture. We could easily increase the width inside the component if it is too small, or what do you think?

**Pull request merged**
