### PR TITLE
Revert "Add support for Monday as first day of the week"

### PR DESCRIPTION
**Pull request by tjohnn**
Reverts tjohnn/vuejs-datetimepicker#11

### CODE REVIEW

**Comment by tjohnn** [comment]
Hi @zerok , It seems some dependencies are missing in your commit. 
And part of my aim is to reduce dependencies on the plugin so the users will not have to go through the stress of npm problem at times. But if the dependency is worth it please add it to the package.json file and commit again.
Thanks.

**Comment by tjohnn** [comment]
date-fns does not seem to be in the dependencies, can you add it or I should?

**Comment by tjohnn** [comment]
Oh okay sorry for the confusion. It maybe it was throwing error due to an error in my set up.
Thanks.

**Comment by zerok** [comment]
Ah ok 🙂 But why did you then reverted my changes again? 😉

**Comment by tjohnn** [comment]
Haha.. I will add it back in a moment

**Comment by tjohnn** [comment]
Can you please confirm if everything is  as supposed, I hope I have not messed up any of your changes

**Pull request merged**
